
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_NANO_ADC(

	//////////// ADC //////////
	output		          		ADC_CONVST,
	output		          		ADC_SCK,
	output		          		ADC_SDI,
	input 		          		ADC_SDO,
	


	//////////// ARDUINO //////////
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,

	//////////// CLOCK //////////
	input 		          		FPGA_CLK1_50,
	input 		          		FPGA_CLK2_50,
	input 		          		FPGA_CLK3_50,

	//////////// HDMI //////////
	inout 		          		HDMI_I2C_SCL,
	inout 		          		HDMI_I2C_SDA,
	inout 		          		HDMI_I2S,
	inout 		          		HDMI_LRCLK,
	inout 		          		HDMI_MCLK,
	inout 		          		HDMI_SCLK,
	output		          		HDMI_TX_CLK,
	output		    [23:0]		HDMI_TX_D,
	output		          		HDMI_TX_DE,
	output		          		HDMI_TX_HS,
	input 		          		HDMI_TX_INT,
	output		          		HDMI_TX_VS,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// SW //////////
	input 		     [3:0]		SW,
	inout 				DAC_SDA,
	inout 				DAC_SCL
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
//wire DEC; //DIGITAL_ERROR_CORRECTION,

wire i2c_serial_scl_in;
wire i2c_serial_sda_in;
wire i2c_serial_scl_oe;
wire i2c_serial_sda_oe;

//=======================================================
//  Structural coding
//=======================================================
DE10_NANO_QSYS u0 (
        .clk_clk                        (FPGA_CLK1_50),     // clk.clk
        .reset_reset_n                  (KEY[0]),           // reset.reset_n
        .sw_external_connection_export  (SW),               // sw_external_connection.export
        .adc_ltc2308_conduit_end_convst (ADC_CONVST),       // adc_ltc2308_conduit_end.CONVST
        .adc_ltc2308_conduit_end_sck    (ADC_SCK),          //.SCK
        .adc_ltc2308_conduit_end_sdi    (ADC_SDI),          //.SDI
        .adc_ltc2308_conduit_end_sdo    (ADC_SDO),           //.SDO
		  .adc_ltc2308_conduit_end_dec    (ARDUINO_IO[8] ),
		  .i2c_dac_serial_sda_in          (i2c_serial_sda_in),          //          i2c_dac_serial.sda_in
			.i2c_dac_serial_scl_in          (i2c_serial_scl_in),
			.i2c_dac_serial_sda_oe          (i2c_serial_sda_oe),          //                        .sda_oe
		.i2c_dac_serial_scl_oe          (i2c_serial_scl_oe)   
    );
	 
//assign i2c_serial_scl_in = DAC_SCL;
//assign DAC_SCL = i2c_serial_scl_oe ? 1'b0 : 1'bz;
//
//assign i2c_serial_sda_in = DAC_SDA;
//assign	DAC_SDA = i2c_serial_sda_oe ? 1'b0 : 1'bz;

assign i2c_serial_scl_in = ARDUINO_IO[15];
assign ARDUINO_IO[15] = i2c_serial_scl_oe ? 1'b0 : 1'bz;

assign i2c_serial_sda_in = ARDUINO_IO[14];
assign	ARDUINO_IO[14] = i2c_serial_sda_oe ? 1'b0 : 1'bz;


//
//assign DEC = ARDUINO_IO[8];
//assign DEC = 0;
assign ARDUINO_IO[7]=1'b1;
assign ARDUINO_IO[6]=ARDUINO_IO[8];
//assign	ARDUINO_IO[14] = i2c_serial_sda_oe ? 1'b0 : 1'bz;


endmodule
