# TCL File Generated by Component Editor 18.1
# Fri Jun 20 17:43:18 BST 2025
# DO NOT MODIFY


# 
# recon_pipe_n "recon_pipe_n" v1.0
#  2025.06.20.17:43:18
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module recon_pipe_n
# 
set_module_property DESCRIPTION ""
set_module_property NAME recon_pipe_n
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME recon_pipe_n
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL reconstruction_top_pipelined_n
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file anti_diff_div.v VERILOG PATH ip/Divs/anti_diff_div.v
add_fileset_file avg_div.v VERILOG PATH ip/Divs/avg_div.v
add_fileset_file mod_divide.v VERILOG PATH ip/Divs/mod_divide.v
add_fileset_file HOD_n.sv SYSTEM_VERILOG PATH ip/Higher_orders/HOD_n.sv
add_fileset_file anti_difference_stage.sv SYSTEM_VERILOG PATH ip/Higher_orders/anti_difference_stage.sv
add_fileset_file top_piped_n2.sv SYSTEM_VERILOG PATH ip/Higher_orders/top_piped_n2.sv TOP_LEVEL_FILE
add_fileset_file adc_to_fixed.sv SYSTEM_VERILOG PATH ip/recon/adc_to_fixed.sv
add_fileset_file fixed_to_dac.sv SYSTEM_VERILOG PATH ip/recon/fixed_to_dac.sv
add_fileset_file modulo_residual_piped.sv SYSTEM_VERILOG PATH ip/recon/modulo_residual_piped.sv
add_fileset_file moving_average.sv SYSTEM_VERILOG PATH ip/recon/moving_average.sv
add_fileset_file anti_difference_rounding.sv SYSTEM_VERILOG PATH ip/recon/anti_difference_rounding.sv


# 
# parameters
# 
add_parameter WIDTH INTEGER 24
set_parameter_property WIDTH DEFAULT_VALUE 24
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter LAMBDA STD_LOGIC_VECTOR 49152
set_parameter_property LAMBDA DEFAULT_VALUE 49152
set_parameter_property LAMBDA DISPLAY_NAME LAMBDA
set_parameter_property LAMBDA TYPE STD_LOGIC_VECTOR
set_parameter_property LAMBDA UNITS None
set_parameter_property LAMBDA ALLOWED_RANGES 0:67108863
set_parameter_property LAMBDA HDL_PARAMETER true
add_parameter FRACTIONAL_BITS INTEGER 16
set_parameter_property FRACTIONAL_BITS DEFAULT_VALUE 16
set_parameter_property FRACTIONAL_BITS DISPLAY_NAME FRACTIONAL_BITS
set_parameter_property FRACTIONAL_BITS TYPE INTEGER
set_parameter_property FRACTIONAL_BITS UNITS None
set_parameter_property FRACTIONAL_BITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FRACTIONAL_BITS HDL_PARAMETER true
add_parameter WINDOW_SIZE INTEGER 100
set_parameter_property WINDOW_SIZE DEFAULT_VALUE 100
set_parameter_property WINDOW_SIZE DISPLAY_NAME WINDOW_SIZE
set_parameter_property WINDOW_SIZE TYPE INTEGER
set_parameter_property WINDOW_SIZE UNITS None
set_parameter_property WINDOW_SIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WINDOW_SIZE HDL_PARAMETER true
add_parameter one_over_a INTEGER 945 ""
set_parameter_property one_over_a DEFAULT_VALUE 945
set_parameter_property one_over_a DISPLAY_NAME one_over_a
set_parameter_property one_over_a TYPE INTEGER
set_parameter_property one_over_a UNITS None
set_parameter_property one_over_a ALLOWED_RANGES -2147483648:2147483647
set_parameter_property one_over_a DESCRIPTION ""
set_parameter_property one_over_a HDL_PARAMETER true


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave clk_en clk_en Input 1
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave adc_in dataa Input 12
add_interface_port nios_custom_instruction_slave n datab Input 2
add_interface_port nios_custom_instruction_slave valid_out done Output 1
add_interface_port nios_custom_instruction_slave dac_out result Output 8
add_interface_port nios_custom_instruction_slave clk clk Input 1
add_interface_port nios_custom_instruction_slave reset reset Input 1

